include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_use_of_protected_member: error
    missing_required_param: error
    missing_return: error

linter:
  rules:
    always_put_control_body_on_new_line: true
    prefer_single_quotes: true
    use_super_parameters: true
